{% set name = "django-q2" %}
{% set version = "1.7.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/django_q2-{{ version }}.tar.gz
  sha256: ab30bbf597cc8ade99ed4deeea37c3ade1c4e5976a61be6452930d14d9ebcd1c

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8,<4.0
    - poetry-core >=1.0.0
    - pip
  run:
    - python >=3.8,<4.0
    - django >=4.2,<6
    - django-picklefield >=3.1.0,<4.0.0
    - importlib-metadata >=3.6
  run_constrained:
    - blessed >=1.19.1,<2.0.0
    - hiredis >=2.0.0,<3.0.0
    - psutil >=5.9.2,<6.0.0
    - django-redis >=5.2.0,<6.0.0
    - iron-mq >=0.9.0,<0.10.0
    - boto3 >=1.24.92,<2.0.0
    - pymongo >=4.2.0,<5.0.0
    - croniter >=2.0.1,<3.0.0
    - django-q-rollbar >=0.1
    - django-q-sentry >=0.1
    - redis-py >=4.3.4,<5.0.0
    - setproctitle >=1.3.2,<2.0.0

test:
  imports:
    - django_q
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/django-q2/django-q2
  doc_url: https://django-q2.readthedocs.org
  summary: A multiprocessing distributed task queue for Django
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
